import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eventism! Browse Event Today",
  description: "Generated by Eventism",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-50">
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
        <ToastContainer 
          position="bottom-right"
          autoClose={3000}
          closeOnClick
          draggable
        />
      </body>
    </html>
  );
}